### ISSUE TITLE
Missing package in metab4script.R

### ISSUE THREAD

**Issue by remondulos** [xia-lab/MetaboAnalyst_Docker#4]
After running the Rscript /metab4script.R command I get an error saying that there is no package pacman:

root@25049a695c07:/# Rscript /metab4script.R
Error in library(pacman) : there is no package called 'pacman'
Execution halted

After trying to install the package pacman I get an error saying that package 'pacman' is not available for R version 3.4.4:
> install.packages("pacman")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Warning message:
package 'pacman' is not available (for R version 3.4.4)

Now I tried to update R to 3.5 with apt-get
sudo apt-get update
sudo apt-get install r-base

Then I get:
r-base : Depends: r-recommended (= 3.5.1-1trusty) but it is not going to be installed

Could you please help.

**Comment by remondulos** [comment]
I managed to update R to 3.5.1 and install pacman. But I still have lots of errors about missing packages that also couldn't be installed. 

Is there a newer version of the docker file that fixes these errors?

**Comment by jsychong** [comment]
MetaboAnalyst still runs on R 3.4.4 due to errors with R serve in 3.5.1. I've updated the docker file to avoid using pacman.
