### ISSUE TITLE
Release Images / other issues

### ISSUE THREAD

**Issue by MatthewTingum** [xia-lab/MetaboAnalyst_Docker#9]
Hello,

Sorry to group multiple issues. I can split these if you'd like.

Is there any way that built docker images could be uploaded to docker hub? The build process takes a long time and can run into problems. Most people here just want to run the server without the hassle.

The docker installs packages 'texlive-full' and 'texlive-latex-extra'. texlive-latex-extra is a part of texlive-full so it can be removed.

Is texlive-full really required? It's the longest part of the build.

The docker could be updated to ubuntu 18.04 -- it's the latest LTS

r-cran-plyr and r-cran-car are available in the ubuntu universe. This means they're not supported by Ubuntu, but rather the community. Maybe we could grab these from the ubuntu universe repository instead?

I agree with the other issue requesting zulu over oracle.

Payara can be updated

MetaboAnalyst can be updated.

echoing into list is not needed when we have 'add-apt-repository'. I assume 'software-properties-common' wasn't installed for no reason.

'DEBIAN_FRONTEND=noninteractive' should be added to the apt-get install commands so things don't hang when repositories change (ideally)

Maybe a verification script runs at the end? A docker file won't fail if one of the R packages fails. We should verify this.

MetaboAnalyst war files can be released on github alongside dropbox releases. This allows people to go back to older builds that behave a certain way.

I'll make a pull request with these changes. Before I do, I want the community input.

**Comment by MADscientist314** [comment]
@MatthewTingum I have been struggling with this docker build for several hours now.  Did you ever get a response from @xia-lab about making these updates?  If nothing else, can you maybe just push an unofficial working container to docker hub so users can just launch the container without having to troubleshooting through the aforementioned dependency error problems (ie: the docker container is still trying to build oracle java 8 with the deprecated installer).  Thanks!

**Comment by jsychong** [comment]
Hi, the dockerfile has been updated and now is available from Docker Hub (jsychong/metaboanalyst)!

**Comment by MatthewTingum** [comment]
@MADscientist314 Hope `jsychong`'s docker works for you! Haven't dealt with `MetaboAnalyst` deployment in a while and I no longer have access to the docker I used.

Feel free to reach out to me for assistance, although I might be slow as this isn't exactly my domain anymore. If I recall correctly, the old docker was set up in such a way that it installs all dependencies when you initialize it. This doesn't have to be the case with dockers, and it should be possible to create one where it "just works" with no installation required. I haven't had a chance to check out the newly provided docker to see if it still does this or not.
